Class {
	#name : #CMMetaSourceLanguage,
	#superclass : #CMMetaEntity,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'Cormas-Metamodel-Famix-Metamodel-Entities'
}

{ #category : #meta }
CMMetaSourceLanguage class >> annotation [

	<FMClass: #SourceLanguage super: #CMMetaEntity>
	<package: #'Cormas-Metamodel-Famix-Metamodel'>
	<generated>
	^ self
]
