Class {
	#name : #CMMetaUnknownSourceLanguage,
	#superclass : #CMMetaSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Cormas-Metamodel-Famix-Metamodel-Entities'
}

{ #category : #meta }
CMMetaUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #CMMetaSourceLanguage>
	<package: #'Cormas-Metamodel-Famix-Metamodel'>
	<generated>
	^ self
]
