Class {
	#name : #CMMetaSourceTextAnchor,
	#superclass : #CMMetaSourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Cormas-Metamodel-Famix-Metamodel-Entities'
}

{ #category : #meta }
CMMetaSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #CMMetaSourceAnchor>
	<package: #'Cormas-Metamodel-Famix-Metamodel'>
	<generated>
	^ self
]
